compctl -k "(
-M \
-O \
-P \
-Q \
-R \
-S \
-V \
-a \
-b \
-f \
-g \
-h \
-m \
-r \
-s \
-t \
-v \
-z \
abs -abs \
acos -acos \
add -add \
addc -addc \
aexpr -aexpr \
aexprf -aexprf \
asin -asin \
atan -atan \
atan2 -atan2 \
bandpass -bandpass \
cat -cat \
chcode -chcode \
chlevel -chlevel \
chlevelc -chlevelc \
chlevelv -chlevelv \
chltype -chltype \
chname -chname \
chparam -chparam \
chtabnum -chtabnum \
consecsum -consecsum \
consects -consects \
const -const \
copy -copy \
cos -cos \
dayavg -dayavg \
daymax -daymax \
daymean -daymean \
daymin -daymin \
daypctl -daypctl \
daystd -daystd \
daysum -daysum \
dayvar -dayvar \
delcode -delcode \
delname -delname \
delparam -delparam \
detrend -detrend \
diff -diff \
diff2 -diff2 \
diffc -diffc \
diffn -diffn \
diffp -diffp \
div -div \
divc -divc \
divdpm -divdpm \
divdpy -divdpy \
dumpmap -dumpmap \
dv2ps -dv2ps \
dv2uv -dv2uv \
dv2uvl -dv2uvl \
eca_cdd -eca_cdd \
eca_cfd -eca_cfd \
eca_csu -eca_csu \
eca_cwd -eca_cwd \
eca_cwdi -eca_cwdi \
eca_cwfi -eca_cwfi \
eca_etr -eca_etr \
eca_fd -eca_fd \
eca_gsl -eca_gsl \
eca_hd -eca_hd \
eca_hwdi -eca_hwdi \
eca_hwfi -eca_hwfi \
eca_id -eca_id \
eca_pd -eca_pd \
eca_r10mm -eca_r10mm \
eca_r20mm -eca_r20mm \
eca_r75p -eca_r75p \
eca_r75ptot -eca_r75ptot \
eca_r90p -eca_r90p \
eca_r90ptot -eca_r90ptot \
eca_r95p -eca_r95p \
eca_r95ptot -eca_r95ptot \
eca_r99p -eca_r99p \
eca_r99ptot -eca_r99ptot \
eca_rr1 -eca_rr1 \
eca_rx1day -eca_rx1day \
eca_rx5day -eca_rx5day \
eca_sdii -eca_sdii \
eca_su -eca_su \
eca_tg10p -eca_tg10p \
eca_tg90p -eca_tg90p \
eca_tn10p -eca_tn10p \
eca_tn90p -eca_tn90p \
eca_tr -eca_tr \
eca_tx10p -eca_tx10p \
eca_tx90p -eca_tx90p \
enlarge -enlarge \
ensavg -ensavg \
ensbrs -ensbrs \
enscrps -enscrps \
ensmax -ensmax \
ensmean -ensmean \
ensmin -ensmin \
enspctl -enspctl \
ensrkhist_space -ensrkhist_space \
ensrkhist_time -ensrkhist_time \
ensroc -ensroc \
ensstd -ensstd \
enssum -enssum \
ensvar -ensvar \
eof -eof \
eofcoeff -eofcoeff \
eofcoeff3d -eofcoeff3d \
eofspatial -eofspatial \
eoftime -eoftime \
eq -eq \
eqc -eqc \
exp -exp \
expr -expr \
exprf -exprf \
fdns -fdns \
filedes -filedes \
fldavg -fldavg \
fldcor -fldcor \
fldmax -fldmax \
fldmean -fldmean \
fldmin -fldmin \
fldpctl -fldpctl \
fldstd -fldstd \
fldsum -fldsum \
fldvar -fldvar \
for -for \
ge -ge \
gec -gec \
genbic -genbic \
genbil -genbil \
gencon -gencon \
gencon2 -gencon2 \
gendis -gendis \
genlaf -genlaf \
gennn -gennn \
gp2sp -gp2sp \
gp2spl -gp2spl \
gradsdes1 -gradsdes1 \
gradsdes2 -gradsdes2 \
gridarea -gridarea \
gridboxavg -gridboxavg \
gridboxmax -gridboxmax \
gridboxmean -gridboxmean \
gridboxmin -gridboxmin \
gridboxstd -gridboxstd \
gridboxsum -gridboxsum \
gridboxvar -gridboxvar \
griddes -griddes \
griddes2 -griddes2 \
griddx -griddx \
griddy -griddy \
gridmask -gridmask \
gridweights -gridweights \
gt -gt \
gtc -gtc \
highpass -highpass \
histcount -histcount \
histfreq -histfreq \
histmean -histmean \
histsum -histsum \
houravg -houravg \
hourmax -hourmax \
hourmean -hourmean \
hourmin -hourmin \
hourpctl -hourpctl \
hourstd -hourstd \
hoursum -hoursum \
hourvar -hourvar \
hurr -hurr \
ifnotthen -ifnotthen \
ifnotthenc -ifnotthenc \
ifthen -ifthen \
ifthenc -ifthenc \
ifthenelse -ifthenelse \
import_amsr -import_amsr \
import_binary -import_binary \
import_cmsaf -import_cmsaf \
import_grads -import_grads \
info -info \
infoc -infoc \
infon -infon \
infop -infop \
input -input \
inputext -inputext \
inputsrv -inputsrv \
int -int \
intlevel -intlevel \
intlevel3d -intlevel3d \
intlevelx -intlevelx \
intlevelx3d -intlevelx3d \
intntime -intntime \
inttime -inttime \
intyear -intyear \
invertlat -invertlat \
invertlatdata -invertlatdata \
invertlatdes -invertlatdes \
invertlev -invertlev \
invertlon -invertlon \
invertlondata -invertlondata \
invertlondes -invertlondes \
le -le \
lec -lec \
ln -ln \
log10 -log10 \
lowpass -lowpass \
lt -lt \
ltc -ltc \
map -map \
mask -mask \
maskindexbox -maskindexbox \
masklonlatbox -masklonlatbox \
maskregion -maskregion \
mastrfu -mastrfu \
max -max \
meravg -meravg \
merge -merge \
mergetime -mergetime \
mermax -mermax \
mermean -mermean \
mermin -mermin \
merpctl -merpctl \
merstd -merstd \
mersum -mersum \
mervar -mervar \
min -min \
ml2hl -ml2hl \
ml2hl_lp -ml2hl_lp \
ml2hlx -ml2hlx \
ml2hlx_lp -ml2hlx_lp \
ml2pl -ml2pl \
ml2pl_lp -ml2pl_lp \
ml2plx -ml2plx \
ml2plx_lp -ml2plx_lp \
monadd -monadd \
monavg -monavg \
mondiv -mondiv \
monmax -monmax \
monmean -monmean \
monmin -monmin \
monmul -monmul \
monpctl -monpctl \
monstd -monstd \
monsub -monsub \
monsum -monsum \
monvar -monvar \
mul -mul \
mulc -mulc \
muldoy -muldoy \
muldpm -muldpm \
muldpy -muldpy \
ncode -ncode \
ndate -ndate \
ne -ne \
nec -nec \
nint -nint \
nlevel -nlevel \
nmon -nmon \
npar -npar \
ntime -ntime \
nyear -nyear \
output -output \
outputarr -outputarr \
outputext -outputext \
outputf -outputf \
outputfld -outputfld \
outputint -outputint \
outputsrv -outputsrv \
outputtab -outputtab \
outputts -outputts \
outputxyz -outputxyz \
pardes -pardes \
partab -partab \
partab2 -partab2 \
pow -pow \
random -random \
reci -reci \
regres -regres \
remap -remap \
remapbic -remapbic \
remapbil -remapbil \
remapcon -remapcon \
remapcon2 -remapcon2 \
remapdis -remapdis \
remapeta -remapeta \
remapeta_s -remapeta_s \
remapeta_z -remapeta_z \
remaplaf -remaplaf \
remapnn -remapnn \
remapsum -remapsum \
replace -replace \
rotuvb -rotuvb \
runavg -runavg \
runmax -runmax \
runmean -runmean \
runmin -runmin \
runpctl -runpctl \
runstd -runstd \
runsum -runsum \
runvar -runvar \
sdiff -sdiff \
seasavg -seasavg \
seasmax -seasmax \
seasmean -seasmean \
seasmin -seasmin \
seaspctl -seaspctl \
seasstd -seasstd \
seassum -seassum \
seasvar -seasvar \
selall -selall \
selcode -selcode \
seldate -seldate \
selday -selday \
selgrid -selgrid \
selhour -selhour \
selindexbox -selindexbox \
sellevel -sellevel \
sellevidx -sellevidx \
sellonlatbox -sellonlatbox \
selltype -selltype \
selmon -selmon \
selname -selname \
selparam -selparam \
selrec -selrec \
selseas -selseas \
selsmon -selsmon \
selstdname -selstdname \
seltabnum -seltabnum \
seltime -seltime \
seltimestep -seltimestep \
selyear -selyear \
selzaxis -selzaxis \
setcalendar -setcalendar \
setcindexbox -setcindexbox \
setclonlatbox -setclonlatbox \
setcode -setcode \
setctomiss -setctomiss \
setdate -setdate \
setday -setday \
setgatt -setgatt \
setgatts -setgatts \
setgrid -setgrid \
setgridarea -setgridarea \
setgridmask -setgridmask \
setgridnumber -setgridnumber \
setgridtype -setgridtype \
sethalo -sethalo \
setlevel -setlevel \
setltype -setltype \
setmisstoc -setmisstoc \
setmissval -setmissval \
setmon -setmon \
setname -setname \
setparam -setparam \
setpartab -setpartab \
setpartabv -setpartabv \
setreftime -setreftime \
setrtoc -setrtoc \
setrtoc2 -setrtoc2 \
setrtomiss -setrtomiss \
settabnum -settabnum \
settaxis -settaxis \
settime -settime \
settunits -settunits \
setvals -setvals \
setvrange -setvrange \
setyear -setyear \
setzaxis -setzaxis \
shifttime -shifttime \
showcode -showcode \
showdate -showdate \
showformat -showformat \
showlevel -showlevel \
showltype -showltype \
showmon -showmon \
showname -showname \
showparam -showparam \
showstdname -showstdname \
showtime -showtime \
showtimestamp -showtimestamp \
showyear -showyear \
sin -sin \
sinfo -sinfo \
sinfoc -sinfoc \
sinfon -sinfon \
sinfop -sinfop \
smooth9 -smooth9 \
sp2gp -sp2gp \
sp2gpl -sp2gpl \
sp2sp -sp2sp \
spcut -spcut \
splitcode -splitcode \
splitday -splitday \
splitgrid -splitgrid \
splithour -splithour \
splitlevel -splitlevel \
splitmon -splitmon \
splitname -splitname \
splitparam -splitparam \
splitrec -splitrec \
splitseas -splitseas \
splitsel -splitsel \
splittabnum -splittabnum \
splityear -splityear \
splitzaxis -splitzaxis \
sqr -sqr \
sqrt -sqrt \
stdatm -stdatm \
strbre -strbre \
strgal -strgal \
strwin -strwin \
sub -sub \
subc -subc \
subtrend -subtrend \
szip -szip \
tan -tan \
temp -temp \
timavg -timavg \
timcor -timcor \
timmax -timmax \
timmean -timmean \
timmin -timmin \
timpctl -timpctl \
timselavg -timselavg \
timselmax -timselmax \
timselmean -timselmean \
timselmin -timselmin \
timselpctl -timselpctl \
timselstd -timselstd \
timselsum -timselsum \
timselvar -timselvar \
timsort -timsort \
timstd -timstd \
timsum -timsum \
timvar -timvar \
topo -topo \
tpnhalo -tpnhalo \
trend -trend \
unsetgridmask -unsetgridmask \
uv2dv -uv2dv \
uv2dvl -uv2dvl \
vct -vct \
vct2 -vct2 \
vertavg -vertavg \
vertmax -vertmax \
vertmean -vertmean \
vertmin -vertmin \
vertstd -vertstd \
vertsum -vertsum \
vertvar -vertvar \
vlist -vlist \
wct -wct \
ydayadd -ydayadd \
ydayavg -ydayavg \
ydaydiv -ydaydiv \
ydaymax -ydaymax \
ydaymean -ydaymean \
ydaymin -ydaymin \
ydaymul -ydaymul \
ydaypctl -ydaypctl \
ydaystd -ydaystd \
ydaysub -ydaysub \
ydaysum -ydaysum \
ydayvar -ydayvar \
ydrunavg -ydrunavg \
ydrunmax -ydrunmax \
ydrunmean -ydrunmean \
ydrunmin -ydrunmin \
ydrunpctl -ydrunpctl \
ydrunstd -ydrunstd \
ydrunsum -ydrunsum \
ydrunvar -ydrunvar \
yearavg -yearavg \
yearmax -yearmax \
yearmean -yearmean \
yearmin -yearmin \
yearpctl -yearpctl \
yearstd -yearstd \
yearsum -yearsum \
yearvar -yearvar \
yhouravg -yhouravg \
yhourmax -yhourmax \
yhourmean -yhourmean \
yhourmin -yhourmin \
yhourstd -yhourstd \
yhoursum -yhoursum \
yhourvar -yhourvar \
ymonadd -ymonadd \
ymonavg -ymonavg \
ymondiv -ymondiv \
ymonmax -ymonmax \
ymonmean -ymonmean \
ymonmin -ymonmin \
ymonmul -ymonmul \
ymonpctl -ymonpctl \
ymonstd -ymonstd \
ymonsub -ymonsub \
ymonsum -ymonsum \
ymonvar -ymonvar \
yseasavg -yseasavg \
yseasmax -yseasmax \
yseasmean -yseasmean \
yseasmin -yseasmin \
yseaspctl -yseaspctl \
yseasstd -yseasstd \
yseassum -yseassum \
yseasvar -yseasvar \
zaxisdes -zaxisdes \
zonavg -zonavg \
zonmax -zonmax \
zonmean -zonmean \
zonmin -zonmin \
zonpctl -zonpctl \
zonstd -zonstd \
zonsum -zonsum \
zonvar -zonvar \
)" -f cdo
