#! /bin/sh
#
# default configuration options and compiler flags for different hosts
#
#
CONFPATH=`echo $0 | cut -c 1-6`
if [ "$CONFPATH" != "../../" ] ; then
CONFPATH='./'
fi
#
if test -z "$1" ; then
  HOSTNAME=`hostname`
else
  HOSTNAME=$1
fi
#
set -x
#
case "${HOSTNAME}" in
# i386-apple-darwin10
    bailung*)
	${CONFPATH}configure --prefix=$HOME/local \
                    --enable-maintainer-mode \
                    --with-jasper=$HOME/local \
                    --with-grib_api=$HOME/local \
                    --with-netcdf=$HOME/local \
                    --with-hdf5=$HOME/local \
                    --with-szlib=$HOME/local \
                    --with-proj=/opt/local \
	            CC=gcc CFLAGS="-g -pipe -D_REENTRANT -Wall -W -Wfloat-equal -pedantic -O2 -fopenmp"
	;;
    hama*)
	${CONFPATH}configure --prefix=$HOME/local \
                    --enable-maintainer-mode \
                    --with-jasper=/opt/local \
                    --with-grib_api=$HOME/local/gribapi-1.9.8 \
                    --with-netcdf=/opt/local \
                    --with-szlib=$HOME/local \
                    --with-proj=/opt/local \
	            CC=gcc CFLAGS="-g -pipe -D_REENTRANT -Wall -W -Wfloat-equal -pedantic -O2 -fopenmp"
	;;
# ia64-xxx-linux
    ds*)
	${CONFPATH}configure --prefix=$HOME/local \
                    --with-netcdf=/pool/ia64/netcdf/netcdf-3.6.0-p1 \
                    --with-szlib=$HOME/local \
                    CC=icc CFLAGS="-g -O2 -Wall -fno-alias -DMIN_BUF_SIZE=4194304"
	;;
    wasser*)
	${CONFPATH}configure --prefix=$HOME/local \
                    --with-netcdf=/home/dkrz/m214089/local/ia64 \
                    CC=icc CFLAGS="-g -O2 -Wall -fno-alias"
	;;
# x86_64-suse-linux
    tornado*)
 	${CONFPATH}configure --prefix=$HOME/local --exec_prefix=$HOME/local/sles10-x64 \
                    --enable-all-static \
	            --with-netcdf=/sw/sles10-x64/netcdf-4.0.1 \
	            --with-hdf5=/sw/sles10-x64/hdf5-1.8.2 \
                    --with-szlib=/sw/sles10-x64/szip-2.1 \
	            CC=gcc CFLAGS='-g -Wall -O2 -fopenmp'
#	            CC=suncc CFLAGS="-g -fast -xopenmp"
	;;
# x86_64-etch-x64-linux
#    squall*)
#        ${CONFPATH}configure --prefix=$HOME/local --exec_prefix=$HOME/local/etch-x64 \
#                    --enable-all-static \
#                    --with-netcdf=/sw/etch-x64/netcdf-4.0.1 \
#                    --with-hdf5=/sw/etch-x64/hdf5-1.8.2 \
#                    --with-szlib=/sw/etch-x64/szip-2.1-static \
#                    --with-proj=/sw/etch-x64/proj-4.7.0 \
#                    CC=gcc CFLAGS='-g -Wall -O2 -fopenmp'
#	;;
# x86_64-lenny-linux-gnu
    squall*)
        ${CONFPATH}configure --prefix=$HOME/local --exec_prefix=$HOME/local/lenny-x64 \
                    --with-netcdf=/sw/lenny-x64/netcdf-4.0.1-gcc \
                    --with-hdf5=/sw/lenny-x64/hdf5-1.8.4p1-gcc \
                    --with-szlib=/sw/lenny-x64/szip-2.1 \
                    --with-proj=/sw/lenny-x64/proj-4.7.0 \
                    CC=gcc CFLAGS='-g -Wall -O2 -fopenmp'
	;;
# x86_64-archlinux
    thingol*)
 	${CONFPATH}configure --prefix=`pwd`/build \
                    --enable-maintainer-mode \
	            --with-netcdf=$HOME/local/libs4cdo-0.0.9 \
	              --with-hdf5=$HOME/local/libs4cdo-0.0.9 \
                     --with-szlib=$HOME/local/libs4cdo-0.0.9 \
                      --with-proj=$HOME/local/libs4cdo-0.0.9 \
                  --with-grib_api=$HOME/local/libs4cdo-0.0.9 \
                    --with-jasper=$HOME/local/libs4cdo-0.0.9 \
                      --with-pic \
	            CC=gcc CFLAGS="-g -Wall -O2 -fopenmp -DWITH_DATA" LIBS=-lopenjpeg
	;;
# i686-suse-linux
    linux | laptop)
	${CONFPATH}configure --prefix=$HOME/local \
                    --with-jasper=/usr \
                    --with-grib_api=$HOME/local \
                    --with-netcdf=$HOME/local \
                    --with-hdf5=$HOME/local \
                    --with-szlib=$HOME/local \
	            CC=colorgcc CFLAGS="-g -Wall -W -Wfloat-equal -pedantic -O2 -fopenmp"
	;;
# i686-linux
    etch-ia32 | gata)
 	${CONFPATH}configure --prefix=$HOME/local --exec_prefix=$HOME/local/etch-ia32 \
                    --enable-maintainer-mode \
                    --with-jasper=/sw/etch-ia32/jasper-1.900.1 \
                    --with-grib_api=$HOME/local/etch-ia32/grib_api-1.9.9 \
	            --with-netcdf=/sw/etch-ia32/netcdf-4.1.1-gcc \
	            --with-hdf5=/sw/etch-ia32/hdf5-1.8.4-threadsafe \
                    --with-zlib=/sw/etch-ia32/zlib-1.2.3 \
                    --with-szlib=$HOME/local/etch-ia32 \
                    --with-proj=/sw/etch-ia32/proj-4.6.0 \
	            CC=gcc CFLAGS="-g -Wall -W -Wfloat-equal -pedantic -O2"
        ;;
# standard workstations at MPI-M x86_64-lenny
    mpipc* )
	${CONFPATH}configure \
               --prefix=`pwd`/build \
               --enable-maintainer-mode \
               --with-netcdf='/sw/lenny-x64/netcdf-latest-gccsys' \
               --with-hdf5='/sw/lenny-x64/hdf5-latest' \
               --with-szlib='/sw/lenny-x64/szip-latest' \
               --with-proj='/sw/lenny-x64/proj-latest' \
               --enable-ruby --enable-swig --enable-python \
	           CC=gcc CFLAGS="-g -fopenmp -Wall -W -Wfloat-equal -pedantic -O2"
        ;;
# dap enabled
    egmont | columbine)
 	  ${CONFPATH}configure --prefix=$HOME/local --exec_prefix=$HOME/local/etch-ia32 \
	            --with-netcdf=/sw/etch-ia32/netcdf-4.1.1-gcc \
	            --with-hdf5=/sw/etch-ia32/hdf5-1.8.4-threadsafe \
                    --with-zlib=/sw/etch-ia32/zlib-1.2.3 \
                    --with-szlib=/sw/etch-ia32/szip-2.1 \
                    --with-proj=/sw/etch-ia32/proj-4.6.0 \
	            --enable-all-static CC=icc CFLAGS="-g -fast -openmp" AR=xiar LD=xild
#	            CC=gcc CFLAGS="-g -Wall -W -Wfloat-equal -pedantic -O2 -fopenmp"
    ;;
# i386-pc-solaris2.10
    grim | mil* )
	${CONFPATH}configure --prefix=$HOME/local --exec_prefix=$HOME/local/solaris10-x86 \
                    --with-netcdf=/client \
                    --with-szlib=$HOME/local/solaris10-x86 \
                    CC=cc CFLAGS="-g -mt -fast"
	;;
# sx6-nec-superux12.2
    cs*)
	${CONFPATH}configure --prefix=$HOME/local \
         	    --with-netcdf=/pool/netcdf/netcdf-3.6.0-p1 \
		    CC=cc \
                    CFLAGS="-O -Onooverlap,restrict=all -pvctl,fullmsg,noassume,loopcnt=1000000"
	;;
    sx6)
	${CONFPATH}configure --host=sx6 --prefix=$HOME/local \
                    --with-netcdf=/pool/SX-6/netcdf/netcdf-3.6.0-p1 \
		    CC=sxcc AR=sxar \
                    CFLAGS="-O -Onooverlap,restrict=all -pvctl,fullmsg,noassume,loopcnt=1000000"
	;;
    es)
	${CONFPATH}configure --host=sx6 --prefix=$HOME/local/ES \
                    --with-netcdf=/S/n010/home010/c0148/local/SX \
		    CC=escc AR=esar \
                    CFLAGS="-O -Onooverlap,restrict=all -pvctl,fullmsg,noassume,loopcnt=1000000"
	;;
# x86_64-unknown-linux-gnu (rhel55)
    lizard*)
        LDFLAGS="-Wl,-rpath=/sw/rhel55-x64/jasper-1.900.1/lib:/sw/rhel55-x64/hdf5-1.8.5-threadsafe/lib:/sw/rhel55-x64/szip-2.1/lib:/sw/rhel55-x64/netcdf-4.1.1/lib -lpng"
        export LDFLAGS
	${CONFPATH}configure --prefix=$HOME/local/rhel55-x64 \
                    --with-jasper=/sw/rhel55-x64/jasper-1.900.1 \
                    --with-grib_api=/sw/rhel55-x64/grib_api-1.9.0 \
                    --with-netcdf=/sw/rhel55-x64/netcdf-4.1.1 \
                    --with-hdf5=/sw/rhel55-x64/hdf5-1.8.5-threadsafe \
                    --with-szlib=/sw/rhel55-x64/szip-2.1 \
                    --with-zlib=/usr \
 	            CC=gcc44 CFLAGS="-g -Wall -O2 -fopenmp"
	;;
# powerpc-ibm-aix5.2.0.0
    ecga*)

	${CONFPATH}configure --prefix=$HOME/local \
                    --with-jasper=/usr/local/lib/metaps/lib/grib_api/jasper_64 \
                    --with-grib_api=$HOME/gribapi/1.9.8 \
                    --with-netcdf=/usr/local/apps/netCDF/3.6.2/LP64 \
                    --with-szlib=$HOME/local \
                    AR="ar -X 64"  LDFLAGS="-brtl" \
	            CC=xlc_r CFLAGS="-g -O3 -q64 -qhot -qstrict -qarch=auto -qtune=auto -qsmp=omp -DHAVE_MMAP -qthreaded"
	;;
# powerpc-ibm-aix5.3.0.0
    blizzard*)
	${CONFPATH}configure --prefix=$HOME/local \
                    --with-jasper=/sw/aix53/jasper-1.900.1 \
                    --with-grib_api=/sw/aix61/ECMWF \
                    --with-netcdf=/sw/aix61/netcdf-4.1.2-hdf5-threadsafe \
                    --with-hdf5=/sw/aix61/hdf5-1.8.6-threadsafe \
                    --with-zlib=/sw/aix53/zlib-1.2.3 \
                    --with-szlib=/sw/aix53/szip-2.1 \
                    --with-proj=/sw/aix53/proj-4.6.1 \
                    AR="ar -X 64"  LDFLAGS="-brtl" \
 	            CC=xlc_r CFLAGS="-g -O3 -q64 -qhot -qstrict -qarch=auto -qtune=auto -qsmp=omp -DHAVE_MMAP -qthreaded"
	;;
    vip*)
	${CONFPATH}configure --prefix=$HOME/local \
                    --with-netcdf=$HOME/local \
                    --with-szlib=$HOME/local \
                    AR="ar -X 64"  LDFLAGS="-brtl" \
	            CC=xlc_r CFLAGS="-g -O3 -q64 -qhot -qstrict -qarch=auto -qtune=auto -qsmp=omp -DHAVE_MMAP -qthreaded"
	;;
# powerpc-ibm-aix6.0.0.0
    c1a*)
	${CONFPATH}configure --prefix=$HOME/local \
                    --with-netcdf=/usr/local/apps/netcdf/3.6.3/LP64 \
                    --with-hdf5=/usr/local/apps/hdf5/1.8.1/LP64 \
                    --with-szlib=/usr/local/apps/szip/2.1/LP64 \
                    AR="ar -X 64"  LDFLAGS="-brtl" \
	            CC=xlc_r CFLAGS="-g -O3 -q64 -qhot -qstrict -qarch=auto -qtune=auto -qsmp=omp -DHAVE_MMAP -qthreaded"
	;;
# powerpc-ibm-aix6.0.0.0
    dwd | p???et01)
	${CONFPATH}configure --prefix=$HOME/local \
                    --with-netcdf=/uhome/mpischul/local \
                    AR="ar -X 64"  LDFLAGS="-brtl" \
	            CC=xlc_r CFLAGS="-g -O3 -q64 -qhot -qstrict -qarch=auto -qtune=auto -qsmp=omp -DHAVE_MMAP -qthreaded"
	;;
    *)
	echo "configuration for hostname $HOSTNAME not found!"
	;;
esac
